import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { ensureSchema, claimName, cleanName } from './lib/leaderboard.js';
import { onRequestPost } from './functions/api/name.js';
const sqlite = new DatabaseSync(':memory:');
const db = { prepare(sql) { return { values: [], bind(...v) { this.values=v; return this; }, async run() { return sqlite.prepare(sql).run(...this.values); }, async first() { return sqlite.prepare(sql).get(...this.values); }, sql }; }, async batch(stmts) { sqlite.exec('BEGIN'); try { for (const s of stmts) sqlite.prepare(s.sql).run(...s.values); sqlite.exec('COMMIT'); } catch(e) { sqlite.exec('ROLLBACK'); throw e; } } };
await ensureSchema(db);
assert.equal(await claimName(db,'alice','Alice'),true);
assert.equal(await claimName(db,'bob','ALICE'),false);
assert.equal(await claimName(db,'alice','alice'),true);
assert.equal(await claimName(db,'alice','NewAlice'),true);
assert.equal(await claimName(db,'bob','Alice'),false);
assert.equal(cleanName('  Alice  '),'Alice');
const insert=sqlite.prepare('INSERT INTO runs (player_id,mode,name,time,created_at,updated_at) VALUES (?,?,?,?,0,0)');
insert.run('alice','auto','Alice',20);
insert.run('alice','scroll','alice',30);
assert.throws(()=>insert.run('bob','auto','ALIce',10),/NAME_TAKEN/);
insert.run('bob','auto','Bob',25);
assert.throws(()=>sqlite.prepare('UPDATE runs SET name=? WHERE player_id=?').run('Alice','bob'),/NAME_TAKEN/);
const request=(token,name)=>new Request('https://example.com/api/name',{method:'POST',body:JSON.stringify({token,name})});
const tokenA='aaaaaaaaaaaaaaaaaaaa', tokenB='bbbbbbbbbbbbbbbbbbbb';
assert.equal((await onRequestPost({request:request(tokenA,'FreshName'),env:{DB:db}})).status,200);
assert.equal((await onRequestPost({request:request(tokenB,' freshname '),env:{DB:db}})).status,409);
assert.equal((await onRequestPost({request:request(tokenA,'FRESHNAME'),env:{DB:db}})).status,200);
assert.equal((await onRequestPost({request:request(tokenA,'!'),env:{DB:db}})).status,400);
console.log('Passed: case-insensitive ownership, retained names, both modes, insert/update guards, and rename API.');
